default_segment: 中立・不明
segments:
  - name: 男性寄り
    keywords:
      - 男性
      - 男
      - メンズ
      - メンズスキンケア
      - メンズファッション
      - 彼女
      - 旦那
      - メンズ美容
      - メンズメイク
      - メンズコスメ
      - ひげ
      - 髭
      - aga
      - 薄毛
      - 育毛
      - 筋トレ
      - プロテイン
      - 車
      - バイク
      - ゴルフ
      - 格闘技
      - ps5
      - ps4
      - steam

  - name: 女性寄り
    keywords:
      - 女性
      - 女
      - レディース
      - レディースファッション
      - 彼氏
      - コスメ
      - メイク
      - スキンケア
      - ネイル
      - 美容液
      - 化粧水
      - ワンピース
      - スカート
      - 婚活
      - 妊娠
      - 出産
      - 生理
      - 育児
